import { beforeEach, expect, it, vi } from 'vitest'
import { flushPromises } from '@vue/test-utils'
import { auth, setTokens } from '../src/store/auth.js'
import { createActivityCalendar } from '../src/api/activityCalendar.js'

const beta = vi.hoisted(() => ({ setIdentity: vi.fn() }))
vi.mock('../src/store/beta.js', () => ({ beta }))
const response = (status, data) => new Response(JSON.stringify({ status_code: status, data }), { status, headers: { 'content-type': 'application/json' } })
const tokens = id => ({ token: 'token-' + id, refresh_token: 'refresh-' + id, user_info: { id } })
function deferred() { let resolve; const promise = new Promise(r => { resolve = r }); return { promise, resolve } }
beforeEach(() => { setTokens(tokens('a')); auth.refreshRejected = false })

it('真实store的迟到A刷新不会覆盖B会话、权限和存储，也不重放旧日历草稿', async () => {
  const late = deferred()
  fetch.mockResolvedValueOnce(response(401)).mockReturnValueOnce(late.promise)
  const outcome = createActivityCalendar({ title: 'A草稿' }).catch(error => error)
  await flushPromises()
  expect(fetch.mock.calls.map(call => call[0])).toEqual(['/v1/admin/activity-calendar', '/user/refresh'])
  setTokens(tokens('b'))
  auth.adminAccess = { permissions: ['activity_calendar:write'] }
  late.resolve(response(200, tokens('a')))
  expect(await outcome).toMatchObject({ code: 'request_identity_changed' })
  expect(auth.userInfo.id).toBe('b')
  expect(auth.accessToken).toBe('token-b')
  expect(auth.refreshToken).toBe('refresh-b')
  expect(JSON.parse(localStorage.getItem('yh_auth')).userInfo.id).toBe('b')
  expect(auth.adminAccess.permissions).toEqual(['activity_calendar:write'])
  expect(fetch).toHaveBeenCalledTimes(2)
})
it('单飞按会话区分：A未返回时B可以刷新，迟到A失败不污染B状态', async () => {
  const late = deferred()
  fetch.mockReturnValueOnce(late.promise).mockResolvedValueOnce(response(200, { ...tokens('b'), token: 'renewed-b' }))
  const a = auth.refresh()
  await flushPromises()
  setTokens(tokens('b'))
  expect(await auth.refresh()).toBe(true)
  late.resolve(response(401))
  expect(await a).toBe(false)
  expect(auth.accessToken).toBe('renewed-b')
  expect(auth.refreshRejected).toBe(false)
})
it('同身份并发刷新仍单飞且日历写入可以正常重放', async () => {
  const late = deferred()
  fetch.mockReturnValueOnce(late.promise)
  const first = auth.refresh(), second = auth.refresh()
  await flushPromises()
  expect(fetch).toHaveBeenCalledTimes(1)
  late.resolve(response(200, { ...tokens('a'), token: 'renewed-a' }))
  expect(await first).toBe(true); expect(await second).toBe(true)
  fetch.mockClear()
  fetch.mockResolvedValueOnce(response(401)).mockResolvedValueOnce(response(200, { ...tokens('a'), token: 'newer-a' })).mockResolvedValueOnce(response(200, {}))
  await createActivityCalendar({ title: '正常草稿' })
  expect(fetch.mock.calls.map(call => call[0])).toEqual(['/v1/admin/activity-calendar', '/user/refresh', '/v1/admin/activity-calendar'])
  expect(fetch.mock.calls[2][1].headers.Authorization).toBe('Bearer newer-a')
})
it('A权限读取迟到不会覆盖B权限，新身份可独立读取，旧finally不清新loading', async () => {
  const lateA = deferred(), lateB = deferred()
  fetch.mockReturnValueOnce(lateA.promise).mockReturnValueOnce(lateB.promise)
  const a = auth.refreshAdminAccess()
  await flushPromises()
  setTokens(tokens('b'))
  expect(auth.adminAccess).toBe(null)
  const b = auth.refreshAdminAccess()
  await flushPromises()
  lateA.resolve(response(200, { permissions: ['admin:role:manage'] }))
  expect(await a).toBe(null)
  expect(auth.adminAccess).toBe(null)
  expect(auth.adminAccessLoading).toBe(true)
  lateB.resolve(response(200, { permissions: ['activity_calendar:write'] }))
  expect((await b).permissions).toEqual(['activity_calendar:write'])
  expect(auth.adminAccess.permissions).toEqual(['activity_calendar:write'])
  expect(auth.adminAccessLoading).toBe(false)
})
