import { beforeEach, expect, it, vi } from 'vitest'
import { flushPromises, mount, RouterLinkStub } from '@vue/test-utils'
import NewSuggestion from '../src/pages/calendar/suggestion-new.vue'
import MySuggestions from '../src/pages/calendar/suggestions.vue'
import Review from '../src/components/calendar/CalendarSuggestionsReview.vue'
import Admin from '../src/pages/calendar/admin.vue'
import Duplicates from '../src/components/calendar/CalendarSuggestionDuplicates.vue'
import * as api from '../src/api/activityCalendar.js'
import { auth } from '../src/store/auth.js'
import { dialog } from '../src/utils/dialog.js'
import { isFeatureEnabled } from '../src/config/features.js'
const route = vi.hoisted(() => ({ query: {} }))
vi.mock('vue-router', () => ({ useRoute: () => route, onBeforeRouteLeave: vi.fn(), onBeforeRouteUpdate: vi.fn() }))
vi.mock('../src/store/auth.js', async () => ({ auth: (await import('vue')).reactive({ accessToken: 'synthetic', userInfo: { id: 'user-a' }, adminAccess: { permissions: ['activity_calendar:write'] } }) }))
vi.mock('../src/utils/dialog.js', () => ({ dialog: { confirm: vi.fn() } }))
vi.mock('../src/config/features.js', async original => ({ ...(await original()), isFeatureEnabled: vi.fn(() => true) }))
vi.mock('../src/api/activityCalendar.js', () => Object.fromEntries(['listActivityCalendar', 'listAdminActivityCalendar', 'createActivityCalendar', 'updateActivityCalendar', 'submitActivityCalendarSuggestion', 'listMyActivityCalendarSuggestions', 'getActivityCalendarSuggestion', 'listAdminActivityCalendarSuggestions', 'acceptActivityCalendarSuggestion', 'rejectActivityCalendarSuggestion'].map(key => [key, vi.fn()])))
const original = patch => ({ game: '如鸢', title: '公告活动', category: 'ACTIVITY', start_date: '2026-10-03', end_date: '2026-10-10', start_time: null, end_time: null, description: '公开介绍', source_url: 'https://example.com/notice', ...patch })
const suggestion = patch => ({ id: 'suggestion-a', original: original(), submission_note: '私人线索', created_at: '2026-10-03T10:00:00Z', status: 'PENDING', version: 0, review_note: null, ...patch })
const render = component => mount(component, { attachTo: document.body, global: { stubs: { IslandSidebar: true, SiteFooter: true, AdminBackLink: true, RouterLink: RouterLinkStub } } })
const button = (wrapper, text) => wrapper.findAll('button').find(node => node.text() === text)
function deferred() { let resolve; const promise = new Promise(r => { resolve = r }); return { promise, resolve } }
async function fill(wrapper) { await wrapper.get('#suggestion-game').setValue('如鸢'); await wrapper.get('#suggestion-title').setValue('公告活动'); await wrapper.get('#suggestion-start_date').setValue('2026-10-03'); await wrapper.get('#suggestion-end_date').setValue('2026-10-10'); await wrapper.get('#suggestion-source_url').setValue('https://example.com/notice') }
async function openReview() { const wrapper = render(Review); await flushPromises(); await button(wrapper, '核对并审核').trigger('click'); await flushPromises(); return wrapper }
beforeEach(() => {
  vi.clearAllMocks(); route.query = {}; isFeatureEnabled.mockReturnValue(true); dialog.confirm.mockResolvedValue(true)
  auth.accessToken = 'synthetic'; auth.userInfo = { id: 'user-a' }; auth.adminAccess = { permissions: ['activity_calendar:write'] }
  api.listActivityCalendar.mockResolvedValue({ items: [] }); api.listAdminActivityCalendar.mockResolvedValue({ items: [] })
  api.listMyActivityCalendarSuggestions.mockResolvedValue({ items: [suggestion()], total: 1 })
  api.listAdminActivityCalendarSuggestions.mockResolvedValue({ items: [suggestion()], total: 1 })
  api.getActivityCalendarSuggestion.mockResolvedValue(suggestion())
  api.submitActivityCalendarSuggestion.mockResolvedValue(suggestion())
  api.acceptActivityCalendarSuggestion.mockResolvedValue(suggestion({ status: 'ACCEPTED', event_id: 'event-a' }))
  api.rejectActivityCalendarSuggestion.mockResolvedValue(suggestion({ status: 'REJECTED' }))
})
it('提交只预填合法游戏，不继承浏览历史日期；字段错误关联摘要焦点并保持资料', async () => {
  route.query = { game: '如鸢', date: '2020-01-01' }
  const wrapper = render(NewSuggestion)
  expect(wrapper.get('#suggestion-game').element.value).toBe('如鸢')
  expect(wrapper.get('#suggestion-start_date').element.value).toBe('')
  await wrapper.get('form').trigger('submit'); await flushPromises()
  expect(api.submitActivityCalendarSuggestion).not.toHaveBeenCalled()
  expect(wrapper.get('#suggestion-title').attributes('aria-invalid')).toBe('true')
  expect(wrapper.get('#suggestion-source_url').attributes('aria-describedby')).toBe('suggestion-error-source_url')
  expect(document.activeElement).toBe(wrapper.get('[role=alert]').element)
  await wrapper.get('[role=alert] a').trigger('click')
  expect(document.activeElement).toBe(wrapper.get('#suggestion-title').element)
  await fill(wrapper); await wrapper.get('#suggestion-submission_note').setValue('私人线索')
  await wrapper.get('form').trigger('submit'); await flushPromises()
  const body = api.submitActivityCalendarSuggestion.mock.lastCall[0]
  expect(body).toMatchObject({ game: '如鸢', submission_note: '私人线索', source_url: 'https://example.com/notice' })
  expect(body.client_request_id).toBeTruthy()
  expect(body).not.toHaveProperty('source_note'); expect(body).not.toHaveProperty('enabled')
  expect(wrapper.text()).toContain('建议编号：suggestion-a')
  expect(document.activeElement).toBe(wrapper.get('[aria-labelledby=suggestion-success]').element)
})
it('结果未知锁住这次资料，重复点击不并发，重试复用payload及请求标识；明确新提交解锁', async () => {
  const late = deferred(); api.submitActivityCalendarSuggestion.mockReturnValueOnce(late.promise)
  const wrapper = render(NewSuggestion); await fill(wrapper)
  await wrapper.get('form').trigger('submit'); await wrapper.get('form').trigger('submit')
  expect(api.submitActivityCalendarSuggestion).toHaveBeenCalledTimes(1)
  late.resolve(Promise.reject(new Error('网络结果未知'))); await flushPromises()
  const first = api.submitActivityCalendarSuggestion.mock.lastCall[0]
  expect(wrapper.get('fieldset').element.disabled).toBe(true)
  api.submitActivityCalendarSuggestion.mockRejectedValueOnce(new Error('仍未知'))
  await wrapper.get('form').trigger('submit'); await flushPromises()
  expect(api.submitActivityCalendarSuggestion.mock.lastCall[0]).toEqual(first)
  dialog.confirm.mockResolvedValueOnce(false)
  await button(wrapper, '开始新的提交').trigger('click'); await flushPromises()
  expect(wrapper.get('fieldset').element.disabled).toBe(true)
  await button(wrapper, '开始新的提交').trigger('click'); await flushPromises()
  expect(wrapper.get('fieldset').element.disabled).toBe(false)
  await wrapper.get('#suggestion-title').setValue('补充后的新活动'); await wrapper.get('form').trigger('submit'); await flushPromises()
  expect(api.submitActivityCalendarSuggestion.mock.lastCall[0].client_request_id).not.toBe(first.client_request_id)
})
it('提交422保留草稿并可修改；身份变化清草稿且迟到成功不出现在B', async () => {
  api.submitActivityCalendarSuggestion.mockRejectedValueOnce(Object.assign(new Error('日期不正确'), { status: 422 }))
  const wrapper = render(NewSuggestion); await fill(wrapper)
  await wrapper.get('form').trigger('submit'); await flushPromises()
  expect(wrapper.get('#suggestion-title').element.value).toBe('公告活动')
  expect(wrapper.get('fieldset').element.disabled).toBe(false)
  const late = deferred(); api.submitActivityCalendarSuggestion.mockReturnValueOnce(late.promise)
  await wrapper.get('form').trigger('submit')
  auth.userInfo = { id: 'user-b' }; await flushPromises()
  late.resolve(suggestion()); await flushPromises()
  expect(wrapper.text()).not.toContain('资料已提交')
  expect(wrapper.get('#suggestion-title').element.value).toBe('')
  auth.accessToken = ''; auth.userInfo = null; await flushPromises()
  expect(wrapper.find('form').exists()).toBe(false)
})
it('功能关闭时三个私有工作区均不读写API；匿名直接挂载也不发送请求', async () => {
  isFeatureEnabled.mockReturnValue(false)
  const wrappers = [render(NewSuggestion), render(MySuggestions), render(Review)]
  await flushPromises()
  expect(api.listMyActivityCalendarSuggestions).not.toHaveBeenCalled()
  expect(api.listAdminActivityCalendarSuggestions).not.toHaveBeenCalled()
  expect(api.submitActivityCalendarSuggestion).not.toHaveBeenCalled()
  wrappers.forEach(wrapper => wrapper.unmount())
  isFeatureEnabled.mockReturnValue(true); auth.userInfo = null; auth.accessToken = ''
  render(NewSuggestion); render(MySuggestions); render(Review); await flushPromises()
  expect(api.listMyActivityCalendarSuggestions).not.toHaveBeenCalled(); expect(api.listAdminActivityCalendarSuggestions).not.toHaveBeenCalled()
})
it('个人列表分页、状态筛选，详情显示只读原始资料、plain采纳快照及当前停用状态', async () => {
  api.listMyActivityCalendarSuggestions.mockResolvedValue({ items: [suggestion()], total: 21 })
  const wrapper = render(MySuggestions); await flushPromises()
  await button(wrapper, '下一页').trigger('click'); await flushPromises()
  expect(api.listMyActivityCalendarSuggestions.mock.lastCall[0]).toMatchObject({ page: 2, page_size: 20 })
  await wrapper.get('select').setValue('ACCEPTED'); await wrapper.get('form').trigger('submit'); await flushPromises()
  expect(api.listMyActivityCalendarSuggestions.mock.lastCall[0]).toMatchObject({ status: 'ACCEPTED', page: 1 })
  api.getActivityCalendarSuggestion.mockResolvedValue(suggestion({ status: 'ACCEPTED', review_note: '已核对公告', reviewed_at: '2026-10-03T12:00:00Z', accepted_snapshot: { ...original({ title: '采纳时标题' }), id: 'event-a' }, current_event: { item: { ...original({ title: '当前标题' }), id: 'event-a' }, enabled: false } }))
  await button(wrapper, '查看资料与审核结果').trigger('click'); await flushPromises()
  expect(wrapper.text()).toContain('原始提交资料（只读）'); expect(wrapper.text()).toContain('私人线索')
  expect(wrapper.text()).toContain('采纳时标题'); expect(wrapper.text()).toContain('当前标题'); expect(wrapper.text()).toContain('活动当前已停用')
  expect(wrapper.findAllComponents(RouterLinkStub).some(link => link.text() === '在日历中查看活动')).toBe(false)
  expect(wrapper.text()).toContain('已核对公告')
  expect(wrapper.find('textarea').exists()).toBe(false)
})
it('个人详情可重试与返回，换身份及选择后迟到详情不覆盖新页面', async () => {
  const wrapper = render(MySuggestions); await flushPromises()
  const late = deferred(); api.getActivityCalendarSuggestion.mockReturnValueOnce(late.promise)
  await button(wrapper, '查看资料与审核结果').trigger('click'); await flushPromises()
  await button(wrapper, '返回我的建议列表').trigger('click'); await flushPromises()
  api.getActivityCalendarSuggestion.mockResolvedValue(suggestion({ id: 'suggestion-b', original: original({ title: 'B详情' }) }))
  await button(wrapper, '查看资料与审核结果').trigger('click'); await flushPromises()
  late.resolve(suggestion({ original: original({ title: '迟到A详情' }) })); await flushPromises()
  expect(wrapper.text()).toContain('B详情'); expect(wrapper.text()).not.toContain('迟到A详情')
  auth.userInfo = { id: 'user-b' }; await flushPromises()
  expect(wrapper.text()).not.toContain('B详情')
  api.getActivityCalendarSuggestion.mockRejectedValueOnce(new Error('详情暂不可用'))
  await button(wrapper, '查看资料与审核结果').trigger('click'); await flushPromises()
  expect(wrapper.text()).toContain('详情暂不可用')
  await button(wrapper, '重试').trigger('click'); await flushPromises()
  expect(wrapper.text()).toContain('B详情')
})
it('管理目录默认不调用建议队列；切换后默认待审分页，审核编辑预填且不复制私人说明', async () => {
  const wrapper = render(Admin); await flushPromises()
  expect(api.listAdminActivityCalendarSuggestions).not.toHaveBeenCalled()
  await button(wrapper, '用户建议').trigger('click'); await flushPromises()
  expect(api.listAdminActivityCalendarSuggestions.mock.lastCall[0]).toEqual({ game: '', status: 'PENDING', page: 1, page_size: 20 })
  await button(wrapper, '核对并审核').trigger('click'); await flushPromises()
  expect(wrapper.get('#review-title').element.value).toBe('公告活动')
  expect(wrapper.get('#review-description').element.value).toBe('公开介绍')
  expect(wrapper.get('#review-source_note').element.value).toBe('')
  await wrapper.get('#review-title').setValue('审核修正标题')
  dialog.confirm.mockResolvedValueOnce(false)
  await button(wrapper, '活动目录').trigger('click'); await flushPromises()
  expect(wrapper.find('#review-title').exists()).toBe(true)
})
it('采纳先确认再发送expected_version与固定时区/启用事件，保持队列筛选；取消不写入', async () => {
  const wrapper = await openReview()
  await wrapper.get('#review-title').setValue('修正活动')
  await wrapper.get('#review-source_note').setValue('管理员来源备注')
  await wrapper.get('#review-review_note').setValue('核对完成')
  dialog.confirm.mockResolvedValueOnce(false)
  await wrapper.get('form').trigger('submit'); await flushPromises()
  expect(api.acceptActivityCalendarSuggestion).not.toHaveBeenCalled()
  await wrapper.get('form').trigger('submit'); await flushPromises()
  expect(api.acceptActivityCalendarSuggestion).toHaveBeenCalledWith('suggestion-a', { expected_version: 0, review_note: '核对完成', event: expect.objectContaining({ title: '修正活动', enabled: true, time_zone: 'Asia/Shanghai', source_note: '管理员来源备注', description: '公开介绍' }) })
  expect(api.acceptActivityCalendarSuggestion.mock.lastCall[1].event).not.toHaveProperty('expected_version')
  expect(wrapper.text()).toContain('建议已采纳')
  expect(wrapper.find('#review-title').exists()).toBe(false)
  expect(api.listAdminActivityCalendarSuggestions.mock.lastCall[0].status).toBe('PENDING')
})
it('不采纳必须填写原因，焦点摘要指向审核说明；拒绝不要求修正活动必填字段', async () => {
  const wrapper = await openReview()
  await button(wrapper, '不采纳').trigger('click'); await flushPromises()
  expect(api.rejectActivityCalendarSuggestion).not.toHaveBeenCalled()
  expect(wrapper.get('#review-review_note').attributes('aria-invalid')).toBe('true')
  expect(document.activeElement).toBe(wrapper.get('[role=alert]').element)
  await wrapper.get('[role=alert] a').trigger('click')
  expect(document.activeElement).toBe(wrapper.get('#review-review_note').element)
  await wrapper.get('#review-title').setValue(''); await wrapper.get('#review-review_note').setValue('请补充公告日期')
  await button(wrapper, '不采纳').trigger('click'); await flushPromises()
  expect(api.rejectActivityCalendarSuggestion).toHaveBeenCalledWith('suggestion-a', { expected_version: 0, review_note: '请补充公告日期' })
})
it('审核409保留编辑，禁止盲重试；刷新状态不覆盖草稿，确认后打开终态', async () => {
  const wrapper = await openReview()
  await wrapper.get('#review-title').setValue('我的审核草稿')
  api.acceptActivityCalendarSuggestion.mockRejectedValueOnce(Object.assign(new Error('conflict'), { status: 409 }))
  await wrapper.get('form').trigger('submit'); await flushPromises()
  expect(wrapper.get('#review-title').element.value).toBe('我的审核草稿')
  expect(button(wrapper, '采纳并加入日历').element.disabled).toBe(true)
  await wrapper.get('form').trigger('submit'); await flushPromises()
  expect(api.acceptActivityCalendarSuggestion).toHaveBeenCalledTimes(1)
  api.getActivityCalendarSuggestion.mockResolvedValue(suggestion({ status: 'REJECTED', review_note: '另一位审核员已处理' }))
  await button(wrapper, '保留草稿并刷新状态').trigger('click'); await flushPromises()
  expect(wrapper.get('#review-title').element.value).toBe('我的审核草稿')
  expect(wrapper.text()).toContain('最新状态：未采纳')
  dialog.confirm.mockResolvedValueOnce(false)
  await button(wrapper, '放弃草稿，打开最新结果').trigger('click'); await flushPromises()
  expect(wrapper.find('#review-title').exists()).toBe(true)
  await button(wrapper, '放弃草稿，打开最新结果').trigger('click'); await flushPromises()
  expect(wrapper.find('#review-title').exists()).toBe(false)
  expect(wrapper.text()).toContain('另一位审核员已处理')
})
it('确认期间换身份或失去权限不写入，并清空列表和草稿；晚读/晚写不能污染新会话', async () => {
  const wrapper = await openReview(), confirmation = deferred()
  dialog.confirm.mockReturnValueOnce(confirmation.promise)
  await wrapper.get('form').trigger('submit')
  auth.adminAccess = { permissions: [] }; await flushPromises()
  confirmation.resolve(true); await flushPromises()
  expect(api.acceptActivityCalendarSuggestion).not.toHaveBeenCalled()
  expect(wrapper.find('#review-title').exists()).toBe(false)
  auth.adminAccess = { permissions: ['activity_calendar:write'] }; await flushPromises()
  const lateRead = deferred(); api.getActivityCalendarSuggestion.mockReturnValueOnce(lateRead.promise)
  await button(wrapper, '核对并审核').trigger('click'); await flushPromises()
  auth.userInfo = { id: 'user-b' }; await flushPromises()
  lateRead.resolve(suggestion({ original: original({ title: '迟到资料' }) })); await flushPromises()
  expect(wrapper.text()).not.toContain('迟到资料')
  await button(wrapper, '核对并审核').trigger('click'); await flushPromises()
  const lateWrite = deferred(); api.acceptActivityCalendarSuggestion.mockReturnValueOnce(lateWrite.promise)
  await wrapper.get('form').trigger('submit'); await flushPromises()
  auth.userInfo = null; auth.accessToken = ''; await flushPromises()
  lateWrite.resolve(suggestion({ status: 'ACCEPTED' })); await flushPromises()
  expect(wrapper.text()).not.toContain('建议已采纳')
})
it('处理队列最后一页最后一条后钳回有效页并保留筛选', async () => {
  api.listAdminActivityCalendarSuggestions.mockResolvedValue({ items: [suggestion()], total: 21 })
  const wrapper = render(Review); await flushPromises()
  await wrapper.findAll('select')[0].setValue('如鸢'); await wrapper.get('form').trigger('submit'); await flushPromises()
  await button(wrapper, '下一页').trigger('click'); await flushPromises()
  await button(wrapper, '核对并审核').trigger('click'); await flushPromises()
  api.listAdminActivityCalendarSuggestions.mockResolvedValueOnce({ items: [], total: 20 }).mockResolvedValueOnce({ items: [suggestion()], total: 20 })
  await wrapper.get('form').trigger('submit'); await flushPromises()
  expect(api.listAdminActivityCalendarSuggestions.mock.calls.at(-2)[0]).toMatchObject({ page: 2, game: '如鸢', status: 'PENDING' })
  expect(api.listAdminActivityCalendarSuggestions.mock.lastCall[0]).toMatchObject({ page: 1, game: '如鸢', status: 'PENDING' })
  expect(wrapper.text()).toContain('第 1 页')
})
it('主动重叠查询仅请求当前游戏与日期，迟到旧区间不覆盖当前检查', async () => {
  const form = original(), late = deferred()
  const wrapper = mount(Duplicates, { props: { form }, global: { stubs: { RouterLink: RouterLinkStub } } })
  api.listActivityCalendar.mockReturnValueOnce(late.promise)
  await button(wrapper, '检查已有活动').trigger('click')
  expect(api.listActivityCalendar.mock.lastCall[0]).toEqual({ game: '如鸢', from: '2026-10-03', to: '2026-10-10' })
  await wrapper.setProps({ form: original({ game: '代号鸢' }) })
  late.resolve({ items: [{ ...original(), id: 'old', title: '旧查询结果' }] }); await flushPromises()
  expect(wrapper.text()).not.toContain('旧查询结果')
  await button(wrapper, '检查已有活动').trigger('click'); await flushPromises()
  expect(wrapper.text()).toContain('没有找到日期重叠的活动')
  expect(api.listActivityCalendar.mock.lastCall[0].game).toBe('代号鸢')
})

it('个人详情在nextTick前身份已切换，不以B身份发送A选中记录的请求', async () => {
  const wrapper = render(MySuggestions); await flushPromises()
  const click = button(wrapper, '查看资料与审核结果').trigger('click')
  auth.userInfo = { id: 'user-b' }
  await click; await flushPromises()
  expect(api.getActivityCalendarSuggestion).not.toHaveBeenCalled()
  expect(wrapper.find('[aria-labelledby=suggestion-detail-title]').exists()).toBe(false)
})
it('卸载清理生命周期，迟到提交不生成结果或触发个人查询', async () => {
  const late = deferred(); api.submitActivityCalendarSuggestion.mockReturnValueOnce(late.promise)
  const wrapper = render(NewSuggestion); await fill(wrapper)
  await wrapper.get('form').trigger('submit'); wrapper.unmount()
  late.resolve(suggestion()); await flushPromises()
  expect(api.listMyActivityCalendarSuggestions).not.toHaveBeenCalled()
  expect(api.submitActivityCalendarSuggestion).toHaveBeenCalledTimes(1)
})

it.each([
  [MySuggestions, 'listMyActivityCalendarSuggestions', '查看资料与审核结果'],
  [Review, 'listAdminActivityCalendarSuggestions', '核对并审核']
])('打开详情后忽略旧列表的迟到失败，不覆盖详情或抢走焦点：%s', async (component, listApi, openText) => {
  const wrapper = render(component); await flushPromises()
  const openButton = button(wrapper, openText), lateList = deferred()
  api[listApi].mockReturnValueOnce(lateList.promise)
  const refresh = wrapper.get('form').trigger('submit')
  const open = openButton.trigger('click')
  await refresh; await open; await flushPromises()
  expect(wrapper.text()).toContain('原始提交资料（只读）')
  const focusedDetail = document.activeElement
  lateList.resolve(Promise.reject(new Error('旧列表迟到失败'))); await flushPromises()
  expect(wrapper.text()).not.toContain('旧列表迟到失败')
  expect(wrapper.text()).toContain('原始提交资料（只读）')
  expect(document.activeElement).toBe(focusedDetail)
})

it('返回个人列表的nextTick期间换身份，仅由新身份初始化列表，不重复请求或旧操作移焦', async () => {
  const wrapper = render(MySuggestions); await flushPromises()
  await button(wrapper, '查看资料与审核结果').trigger('click'); await flushPromises()
  api.listMyActivityCalendarSuggestions.mockClear()
  const close = button(wrapper, '返回我的建议列表').trigger('click')
  auth.userInfo = { id: 'user-b' }
  await close; await flushPromises()
  expect(api.listMyActivityCalendarSuggestions).toHaveBeenCalledTimes(1)
  expect(wrapper.find('[aria-labelledby=suggestion-detail-title]').exists()).toBe(false)
  expect(document.activeElement).not.toBe(wrapper.get('[aria-labelledby=my-suggestions-title]').element)
})
