import { beforeEach, expect, it, vi } from 'vitest'
import { flushPromises, mount, RouterLinkStub } from '@vue/test-utils'
import Admin from '../src/pages/calendar/admin.vue'
import * as api from '../src/api/activityCalendar.js'
import { auth } from '../src/store/auth.js'
import { dialog } from '../src/utils/dialog.js'
import { isFeatureEnabled } from '../src/config/features.js'
import { getVisibleAdminTools } from '../src/utils/adminTools.js'

vi.mock('../src/store/auth.js', async () => ({ auth: (await import('vue')).reactive({ accessToken: 'synthetic', userInfo: { id: 'admin-a' }, adminAccess: { permissions: ['activity_calendar:write'] } }) }))
vi.mock('vue-router', () => ({ onBeforeRouteLeave: vi.fn(), onBeforeRouteUpdate: vi.fn() }))
vi.mock('../src/utils/dialog.js', () => ({ dialog: { confirm: vi.fn() } }))
vi.mock('../src/config/features.js', async importOriginal => ({ ...(await importOriginal()), isFeatureEnabled: vi.fn(() => true) }))
vi.mock('../src/api/activityCalendar.js', () => ({ listAdminActivityCalendar: vi.fn(), createActivityCalendar: vi.fn(), updateActivityCalendar: vi.fn() }))
const item = (patch = {}) => ({ id: 'evt-a', title: '手工活动', game: '如鸢', category: 'ACTIVITY', start_date: '2026-10-03', end_date: '2026-10-10', source_type: 'MANUAL', ...patch })
const entry = (patch = {}) => ({ item: item(), version: 0, enabled: true, read_only: false, source_note: '整理备注', updated_at: '2026-10-03T10:00:00Z', ...patch })
const render = () => mount(Admin, { attachTo: document.body, global: { stubs: { IslandSidebar: true, SiteFooter: true, AdminBackLink: true, RouterLink: RouterLinkStub } } })
const button = (wrapper, text) => wrapper.findAll('button').find(node => node.text() === text)
const filter = (wrapper, label) => wrapper.findAll('label').find(node => node.text().startsWith(label)).find('input, select')
function deferred() { let resolve; const promise = new Promise(r => { resolve = r }); return { promise, resolve } }
beforeEach(() => {
  vi.clearAllMocks(); isFeatureEnabled.mockReturnValue(true); dialog.confirm.mockResolvedValue(true)
  auth.accessToken = 'synthetic'; auth.userInfo = { id: 'admin-a' }; auth.adminAccess = { permissions: ['activity_calendar:write'] }
  api.listAdminActivityCalendar.mockResolvedValue({ items: [entry()] })
  api.createActivityCalendar.mockResolvedValue(entry()); api.updateActivityCalendar.mockResolvedValue(entry({ version: 1 }))
})

it('缺权限或关闭flag时不读写管理员API，也不暴露管理工具', async () => {
  auth.adminAccess = { permissions: [] }
  const wrapper = render(); await flushPromises()
  expect(wrapper.text()).toContain('需要活动日历维护权限')
  expect(api.listAdminActivityCalendar).not.toHaveBeenCalled()
  expect(getVisibleAdminTools(auth.adminAccess)).toEqual([])
  wrapper.unmount()
  auth.adminAccess = { permissions: ['activity_calendar:write'] }; isFeatureEnabled.mockReturnValue(false)
  render(); await flushPromises()
  expect(api.listAdminActivityCalendar).not.toHaveBeenCalled()
  expect(getVisibleAdminTools(auth.adminAccess)).toEqual([])
  expect(api.createActivityCalendar).not.toHaveBeenCalled()
  expect(api.updateActivityCalendar).not.toHaveBeenCalled()
})
it('列表筛选提交API，独立编辑器与列表互斥，保存携带version=0并保留筛选', async () => {
  const wrapper = render(); await flushPromises()
  await filter(wrapper, '游戏').setValue('如鸢')
  await filter(wrapper, '类型').setValue('ACTIVITY')
  await filter(wrapper, '启用状态').setValue('true')
  await filter(wrapper, '日期范围起点').setValue('2026-10-01')
  await filter(wrapper, '日期范围终点').setValue('2026-10-15')
  await filter(wrapper, '搜索标题').setValue('活动')
  await wrapper.get('form').trigger('submit'); await flushPromises()
  expect(api.listAdminActivityCalendar.mock.lastCall[0]).toEqual({ game: '如鸢', category: 'ACTIVITY', enabled: 'true', from: '2026-10-01', to: '2026-10-15', search: '活动' })
  await button(wrapper, '编辑活动').trigger('click')
  expect(wrapper.find('.calendar-list').exists()).toBe(false)
  expect(document.activeElement).toBe(wrapper.get('.calendar-editor').element)
  expect(wrapper.get('#calendar-category').text()).not.toContain('招募')
  await wrapper.get('#calendar-title').setValue('修改后的活动')
  await wrapper.get('form').trigger('submit'); await flushPromises()
  expect(api.updateActivityCalendar).toHaveBeenCalledWith('evt-a', expect.objectContaining({ expected_version: 0, title: '修改后的活动', source_note: '整理备注', enabled: true }))
  expect(wrapper.find('.calendar-editor').exists()).toBe(false)
  expect(filter(wrapper, '搜索标题').element.value).toBe('活动')
  expect(wrapper.text()).toContain('活动已保存')
})
it('只读招募永不显示编辑按钮；仅双权限提供管理跳转', async () => {
  api.listAdminActivityCalendar.mockResolvedValue({ items: [entry({ item: item({ id: 'recruitment:pool', source_type: 'RECRUITMENT_POOL', category: 'RECRUITMENT' }), read_only: true, version: null })] })
  const wrapper = render(); await flushPromises()
  expect(wrapper.text()).toContain('来自招募卡池 · 只读')
  expect(button(wrapper, '编辑活动')).toBeUndefined()
  expect(wrapper.findComponent(RouterLinkStub).exists()).toBe(false)
  auth.adminAccess = { permissions: ['activity_calendar:write', 'recruitment_catalog:write'] }; await flushPromises()
  expect(wrapper.getComponent(RouterLinkStub).props('to')).toBe('/recruitment/admin')
  expect(api.updateActivityCalendar).not.toHaveBeenCalled()
})
it('字段错误内联并聚焦摘要，新建payload不含expected_version', async () => {
  const wrapper = render(); await flushPromises()
  await button(wrapper, '新建活动').trigger('click')
  await wrapper.get('form').trigger('submit'); await flushPromises()
  expect(wrapper.get('#calendar-title').attributes('aria-invalid')).toBe('true')
  expect(wrapper.get('#error-title').text()).toContain('标题')
  expect(document.activeElement).toBe(wrapper.get('[role=alert]').element)
  await wrapper.get('[role=alert] a').trigger('click')
  expect(document.activeElement).toBe(wrapper.get('#calendar-title').element)
  expect(api.createActivityCalendar).not.toHaveBeenCalled()
  await wrapper.get('#calendar-title').setValue('新建活动')
  await wrapper.get('#calendar-start_date').setValue('2026-10-03')
  await wrapper.get('#calendar-end_date').setValue('2026-10-10')
  await wrapper.get('form').trigger('submit'); await flushPromises()
  expect(api.createActivityCalendar).toHaveBeenCalledTimes(1)
  expect(api.createActivityCalendar.mock.lastCall[0]).not.toHaveProperty('expected_version')
})
it('精确时间成对校验；取消开关后完整替换清除旧时间', async () => {
  const wrapper = render(); await flushPromises()
  await button(wrapper, '编辑活动').trigger('click')
  await wrapper.findAll('input[type=checkbox]')[0].setValue(true)
  await wrapper.get('#calendar-start_time').setValue('09:00')
  await wrapper.get('form').trigger('submit'); await flushPromises()
  expect(wrapper.get('#error-end_time').text()).toContain('成对')
  expect(api.updateActivityCalendar).not.toHaveBeenCalled()
  await wrapper.findAll('input[type=checkbox]')[0].setValue(false)
  await wrapper.get('form').trigger('submit'); await flushPromises()
  expect(api.updateActivityCalendar.mock.lastCall[1]).toMatchObject({ start_time: null, end_time: null })
})
it('409保留草稿并阻止旧版本重试，显式刷新前先确认放弃', async () => {
  api.updateActivityCalendar.mockRejectedValue(Object.assign(new Error('conflict'), { status: 409 }))
  const wrapper = render(); await flushPromises()
  await button(wrapper, '编辑活动').trigger('click')
  await wrapper.get('#calendar-title').setValue('保留草稿')
  await wrapper.get('form').trigger('submit'); await flushPromises()
  expect(wrapper.get('#calendar-title').element.value).toBe('保留草稿')
  expect(wrapper.get('[role=alert]').text()).toContain('内容已被其他人修改，请刷新后重试')
  expect(document.activeElement).toBe(wrapper.get('[role=alert]').element)
  expect(button(wrapper, '保存活动').element.disabled).toBe(true)
  await wrapper.get('form').trigger('submit'); await flushPromises()
  expect(api.updateActivityCalendar).toHaveBeenCalledTimes(1)
  dialog.confirm.mockResolvedValueOnce(false)
  await button(wrapper, '返回目录并刷新').trigger('click'); await flushPromises()
  expect(wrapper.find('.calendar-editor').exists()).toBe(true)
  await button(wrapper, '返回目录并刷新').trigger('click'); await flushPromises()
  expect(wrapper.find('.calendar-editor').exists()).toBe(false)
  expect(api.listAdminActivityCalendar).toHaveBeenCalledTimes(2)
})
it('停用确认取消不写入，确认后提交enabled=false；重新启用无需删除', async () => {
  const wrapper = render(); await flushPromises()
  await button(wrapper, '编辑活动').trigger('click')
  await wrapper.findAll('input[type=checkbox]')[1].setValue(false)
  dialog.confirm.mockResolvedValueOnce(false)
  await wrapper.get('form').trigger('submit'); await flushPromises()
  expect(api.updateActivityCalendar).not.toHaveBeenCalled()
  await wrapper.get('form').trigger('submit'); await flushPromises()
  expect(api.updateActivityCalendar.mock.lastCall[1].enabled).toBe(false)
  expect(dialog.confirm).toHaveBeenCalledWith(expect.objectContaining({ title: '停用这个活动？' }))
  api.listAdminActivityCalendar.mockResolvedValue({ items: [entry({ enabled: false })] })
  await wrapper.get('form').trigger('submit'); await flushPromises()
  await button(wrapper, '编辑活动').trigger('click')
  await wrapper.findAll('input[type=checkbox]')[1].setValue(true)
  await wrapper.get('form').trigger('submit'); await flushPromises()
  expect(api.updateActivityCalendar.mock.lastCall[1].enabled).toBe(true)
})
it('权限/身份切换丢弃草稿和迟到读写；确认期间失去权限不得写入', async () => {
  const late = deferred()
  const wrapper = render(); await flushPromises()
  await button(wrapper, '编辑活动').trigger('click')
  await wrapper.get('#calendar-title').setValue('旧身份草稿')
  api.updateActivityCalendar.mockReturnValueOnce(late.promise)
  await wrapper.get('form').trigger('submit')
  auth.userInfo = { id: 'admin-b' }; await flushPromises()
  late.resolve(entry()); await flushPromises()
  expect(wrapper.text()).not.toContain('活动已保存')
  expect(wrapper.text()).not.toContain('旧身份草稿')
  const read = deferred(); api.listAdminActivityCalendar.mockReturnValueOnce(read.promise)
  auth.userInfo = { id: 'admin-c' }; await flushPromises()
  auth.adminAccess = { permissions: [] }; await flushPromises()
  read.resolve({ items: [entry()] }); await flushPromises()
  expect(wrapper.find('.calendar-list').exists()).toBe(false)
  auth.adminAccess = { permissions: ['activity_calendar:write'] }; await flushPromises()
  await button(wrapper, '编辑活动').trigger('click')
  await wrapper.findAll('input[type=checkbox]')[1].setValue(false)
  const confirmation = deferred(); dialog.confirm.mockReturnValueOnce(confirmation.promise)
  api.updateActivityCalendar.mockClear()
  await wrapper.get('form').trigger('submit')
  auth.adminAccess = { permissions: [] }; await flushPromises()
  confirmation.resolve(true); await flushPromises()
  expect(api.updateActivityCalendar).not.toHaveBeenCalled()
})
it('列表网络错误可刷新，倒置日期范围不发送请求，保存网络错误保留草稿', async () => {
  api.listAdminActivityCalendar.mockRejectedValueOnce(new Error('读取失败'))
  const wrapper = render(); await flushPromises()
  expect(wrapper.text()).toContain('读取失败')
  await wrapper.get('form').trigger('submit'); await flushPromises()
  await filter(wrapper, '日期范围起点').setValue('2026-10-10')
  await filter(wrapper, '日期范围终点').setValue('2026-10-01')
  await wrapper.get('form').trigger('submit'); await flushPromises()
  expect(api.listAdminActivityCalendar).toHaveBeenCalledTimes(2)
  expect(wrapper.text()).toContain('终点不能早于起点')
  await filter(wrapper, '日期范围终点').setValue('2026-10-20')
  await wrapper.get('form').trigger('submit'); await flushPromises()
  await button(wrapper, '编辑活动').trigger('click')
  api.updateActivityCalendar.mockRejectedValueOnce(new Error('网络失败'))
  await wrapper.get('form').trigger('submit'); await flushPromises()
  expect(wrapper.find('.calendar-editor').exists()).toBe(true)
  expect(wrapper.text()).toContain('网络失败')
})
